In [120]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pickle

In [121]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [122]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 77 columns):
Unnamed: 0                               15661 non-null int64
Unnamed: 0.1                             15661 non-null int64
Completion Term                          9893 non-null object
Completion Term Academic Year            9893 non-null float64
Completion Term Calendar Year            9893 non-null float64
Program Campus Code                      9895 non-null object
Academic Group Code                      10371 non-null object
Plan Academic Organization Code          10371 non-null object
Degree Code                              11062 non-null object
Degree Type                              14645 non-null object
Academic Plan Code                       15661 non-null object
Scholar Age Range End Completion Term    15661 non-null object
Cumulative GPA Range                     15661 non-null object
Adult Learner Flag                       15661 non-null object
Scholar Age E

In [123]:
train['id'] = range(1, len(train)+1)

In [124]:
test['id'] = range(len(train)+1, len(train)+1+len(test))

In [125]:
train = train[pd.notnull(train['Salary'])]
test = test[pd.notnull(test['Salary'])]

In [126]:
train['Salary Range'].unique()

array(['70K to 79,999', '30K to 39,999', '40K to 49,999', '60K to 69,999',
       '50K to 59,999', '20K to 29,999', '80K to 89,999',
       '100K and above', '90K to 99,999', 'Under 20K'], dtype=object)

In [127]:
from sklearn.preprocessing import LabelEncoder
lenc = LabelEncoder()
train['Salary Range'].replace(to_replace = 'Under 20K', value = 0, inplace = True)
train['Salary Range'].replace(to_replace = '20K to 29,999', value = 1, inplace = True)
train['Salary Range'].replace(to_replace = '30K to 39,999', value = 2, inplace = True)
train['Salary Range'].replace(to_replace = '40K to 49,999', value = 3, inplace = True)
train['Salary Range'].replace(to_replace = '50K to 59,999', value = 4, inplace = True)
train['Salary Range'].replace(to_replace = '60K to 69,999', value = 5, inplace = True)
train['Salary Range'].replace(to_replace = '70K to 79,999', value = 6, inplace = True)
train['Salary Range'].replace(to_replace = '80K to 89,999', value = 7, inplace = True)
train['Salary Range'].replace(to_replace = '90K to 99,999', value = 8, inplace = True)
train['Salary Range'].replace(to_replace = '100K and above', value = 9, inplace = True)

test['Salary Range'].replace(to_replace = 'Under 20K', value = 0, inplace = True)
test['Salary Range'].replace(to_replace = '20K to 29,999', value = 1, inplace = True)
test['Salary Range'].replace(to_replace = '30K to 39,999', value = 2, inplace = True)
test['Salary Range'].replace(to_replace = '40K to 49,999', value = 3, inplace = True)
test['Salary Range'].replace(to_replace = '50K to 59,999', value = 4, inplace = True)
test['Salary Range'].replace(to_replace = '60K to 69,999', value = 5, inplace = True)
test['Salary Range'].replace(to_replace = '70K to 79,999', value = 6, inplace = True)
test['Salary Range'].replace(to_replace = '80K to 89,999', value = 7, inplace = True)
test['Salary Range'].replace(to_replace = '90K to 99,999', value = 8, inplace = True)
test['Salary Range'].replace(to_replace = '100K and above', value = 9, inplace = True)

In [128]:
test['Salary Range'].unique()

array([4, 5, 2, 9, 3, 6, 0, 1, 7, 8])

In [129]:
train['Int Exp Type'].fillna('None', inplace = True)
test['Int Exp Type'].fillna('None', inplace = True)

In [130]:
train['Intern Paid Flag'].fillna('N', inplace = True)
test['Intern Paid Flag'].fillna('N', inplace = True)

In [131]:
train['Employed During Education Flag'].fillna('N', inplace = True)
test['Employed During Education Flag'].fillna('N', inplace = True)

In [132]:
major = np.append(train['Academic Plan Code'], test['Academic Plan Code']).reshape(-1,1)
gpaRange = np.append(train['Cumulative GPA Range'], test['Cumulative GPA Range']).reshape(-1,1)
gender = np.append(train['Scholar Gender'], test['Scholar Gender']).reshape(-1,1)
race = np.append(train['Scholar IPEDS Race/Ethnicity Code'], test['Scholar IPEDS Race/Ethnicity Code']).reshape(-1,1)
paidIntern = np.append(train['Intern Paid Flag'], test['Intern Paid Flag']).reshape(-1,1)
honors = np.append(train['Honors Code'], test['Honors Code']).reshape(-1,1)
employedDuring = np.append(train['Employed During Education Flag'], test['Employed During Education Flag']).reshape(-1,1)
extra = np.append(train['Int Exp Type'], test['Int Exp Type']).reshape(-1,1)
found = np.append(train['Employment Learned About Code'], test['Employment Learned About Code']).reshape(-1,1)
age = np.append(train['Scholar Age End Completion Term'], test['Scholar Age End Completion Term']).reshape(-1, 1)

salary = train['Salary'].values
testSal = test['Salary'].values


salaryRange = train['Salary Range'].values

# major = np.append(train['Academic.Plan.Code'], test['Academic.Plan.Code']).reshape(-1,1)
# gpaRange = np.append(train['Cumulative.GPA.Range'], test['Cumulative.GPA.Range']).reshape(-1,1)
# gender = np.append(train['Scholar.Gender'], test['Scholar.Gender']).reshape(-1,1)
# race = np.append(train['Scholar.IPEDS.Race.Ethnicity.Code'], test['Scholar.IPEDS.Race.Ethnicity.Code']).reshape(-1,1)
# paidIntern = np.append(train['Intern.Paid.Flag'], test['Intern.Paid.Flag']).reshape(-1,1)
# honors = np.append(train['Honors.Code'], test['Honors.Code']).reshape(-1,1)
# employedDuring = np.append(train['Employed.During.Education.Flag'], test['Employed.During.Education.Flag']).reshape(-1,1)
# extra = np.append(train['Int.Exp.Type'], test['Int.Exp.Type']).reshape(-1,1)
# found = np.append(train['Employment.Learned.About.Code'], test['Employment.Learned.About.Code']).reshape(-1,1)
# age = np.append(train['Scholar.Age.End.Completion.Term'], test['Scholar.Age.End.Completion.Term']).reshape(-1, 1)

# salaryRange = train['Salary.Range'].values

In [133]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

labelEncoder = LabelEncoder()
oneHotEncoder = OneHotEncoder()

In [134]:
j = 0
for i in salary:
    if i < 20000:
        salary[j] = 0
    elif i >= 20000 and i < 25000:
        salary[j] = 1
    elif i >= 25000 and i < 30000:
        salary[j] = 2
    elif i >= 30000 and i < 35000:
        salary[j] = 3
    elif i >= 35000 and i < 40000:
        salary[j] = 4
    elif i >= 40000 and i < 45000:
        salary[j] = 5
    elif i >= 45000 and i < 50000:
        salary[j] = 6
    elif i >= 50000 and i < 55000:
        salary[j] = 7
    elif i >= 55000 and i < 60000:
        salary[j] = 8
    elif i >= 60000 and i < 65000:
        salary[j] = 9
    elif i >= 70000 and i < 75000:
        salary[j] = 10
    elif i >= 75000 and i < 80000:
        salary[j] = 11
    elif i >= 85000 and i < 90000:
        salary[j] = 12
    elif i >= 95000 and i < 100000:
        salary[j] = 13
    else:
        salary[j] = 14
    j = j +1

In [135]:
j = 0
for i in testSal:
    if i < 20000:
        testSal[j] = 0
    elif i >= 20000 and i < 25000:
        testSal[j] = 1
    elif i >= 25000 and i < 30000:
        testSal[j] = 2
    elif i >= 30000 and i < 35000:
        testSal[j] = 3
    elif i >= 35000 and i < 40000:
        testSal[j] = 4
    elif i >= 40000 and i < 45000:
        testSal[j] = 5
    elif i >= 45000 and i < 50000:
        testSal[j] = 6
    elif i >= 50000 and i < 55000:
        testSal[j] = 7
    elif i >= 55000 and i < 60000:
        testSal[j] = 8
    elif i >= 60000 and i < 65000:
        testSal[j] = 9
    elif i >= 70000 and i < 75000:
        testSal[j] = 10
    elif i >= 75000 and i < 80000:
        testSal[j] = 11
    elif i >= 85000 and i < 90000:
        testSal[j] = 12
    elif i >= 95000 and i < 100000:
        testSal[j] = 13
    else:
        testSal[j] = 14
    j = j +1

In [136]:
salary.size

15661

In [137]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15661 entries, 0 to 15660
Data columns (total 78 columns):
Unnamed: 0                               15661 non-null int64
Unnamed: 0.1                             15661 non-null int64
Completion Term                          9893 non-null object
Completion Term Academic Year            9893 non-null float64
Completion Term Calendar Year            9893 non-null float64
Program Campus Code                      9895 non-null object
Academic Group Code                      10371 non-null object
Plan Academic Organization Code          10371 non-null object
Degree Code                              11062 non-null object
Degree Type                              14645 non-null object
Academic Plan Code                       15661 non-null object
Scholar Age Range End Completion Term    15661 non-null object
Cumulative GPA Range                     15661 non-null object
Adult Learner Flag                       15661 non-null object
Scholar Age E

In [138]:
test['newSalRange'] = testSal

In [139]:
major = labelEncoder.fit_transform(major)
gpaRange = labelEncoder.fit_transform(gpaRange)
gender = labelEncoder.fit_transform(gender)
race = labelEncoder.fit_transform(race)
paidIntern = labelEncoder.fit_transform(paidIntern)
honors = labelEncoder.fit_transform(honors)
employedDuring = labelEncoder.fit_transform(employedDuring)
extra = labelEncoder.fit_transform(extra)

/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [140]:
major = major.reshape(-1,1)
gpaRange = gpaRange.reshape(-1,1)
gender = gender.reshape(-1,1)
race = race.reshape(-1,1)
paidIntern = paidIntern.reshape(-1,1)

honors = honors.reshape(-1,1)
employedDuring = employedDuring.reshape(-1,1)
extra = extra.reshape(-1,1)

# target
salaryRange = salaryRange.reshape(-1,1)

In [141]:
# set up features and labels
X = np.hstack((major, gpaRange, gender, race, paidIntern, extra, age, found, employedDuring))
# X = np.hstack((major, gender, race, paidIntern, extra, found, employedDuring))
y = salary
m = y.size

In [142]:
# create KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, weights ='distance')
knn.fit(X[:m], y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='distance')

In [143]:
from sklearn.linear_model import SGDClassifier
lcm = SGDClassifier()
lcm.fit(X[:m], y)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [144]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy')
dtc.fit(X[:m], y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [145]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X[:m], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [146]:
# see performance on training set
from sklearn.metrics import accuracy_score
accuracy_score(y, knn.predict(X[:m]))

0.867122150565098

In [147]:
lcm.predict([[371.,   3.,   1.,   8.,   1.,   2.,  22.,   3.,   1.]])

array([14.])

In [148]:
X[m+31].reshape(1,-1)

array([[371.,   3.,   1.,   8.,   1.,   2.,  22.,   3.,   1.]])

In [149]:
accuracy_score(y, dtc.predict(X[:m]))

0.8702509418300236

In [150]:
X[m+30].reshape(-1,1)

array([[589.],
       [  2.],
       [  1.],
       [  8.],
       [  1.],
       [  2.],
       [ 22.],
       [  5.],
       [  0.]])

In [151]:
accuracy_score(y, rf.predict(X[:m]))

0.8524998403677926

In [152]:
idArr = np.asarray(test['id'])
Sal = np.asarray(test['newSalRange'])

In [153]:
predictions = (knn.predict(X[m:]))
predictions = np.hstack((idArr.reshape(-1,1), 
                         predictions.reshape(-1,1), Sal.reshape(-1,1)))

predictions = np.vstack((np.array([['id','guess','answer']]),
                        predictions))

np.savetxt('checksheetKNN.csv',
          predictions,
          delimiter=',',
           fmt='%s')

In [154]:
predictions = (lcm.predict(X[m:]))
predictions = np.hstack((idArr.reshape(-1,1), 
                         predictions.reshape(-1,1), Sal.reshape(-1,1)))

predictions = np.vstack((np.array([['id','guess','answer']]),
                        predictions))

np.savetxt('checksheetLCM.csv',
          predictions,
          delimiter=',',
           fmt='%s')

In [155]:
predictions = (dtc.predict(X[m:]))
predictions = np.hstack((idArr.reshape(-1,1), 
                         predictions.reshape(-1,1), Sal.reshape(-1,1)))

predictions = np.vstack((np.array([['id','guess','answer']]),
                        predictions))

np.savetxt('checksheetDTC.csv',
          predictions,
          delimiter=',',
           fmt='%s')

In [156]:
predictions = (rf.predict(X[m:]))
predictions = np.hstack((idArr.reshape(-1,1), 
                         predictions.reshape(-1,1), Sal.reshape(-1,1)))

predictions = np.vstack((np.array([['id','guess','answer']]),
                        predictions))

np.savetxt('checksheetRF.csv',
          predictions,
          delimiter=',',
           fmt='%s')

In [157]:
pickle.dump(knn, open('knn_pickle.pkl', 'wb'))